[package]
name = "solana-core"
description = "Blockchain, Rebuilt for Scale"
version = "1.9.15"
homepage = "https://solana.com/"
documentation = "https://docs.rs/solana-core"
readme = "../README.md"
repository = "https://github.com/solana-labs/solana"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
license = "Apache-2.0"
edition = "2021"

[badges]
codecov = { repository = "solana-labs/solana", branch = "master", service = "github" }

[dependencies]
ahash = "0.7.6"
base64 = "0.12.3"
bincode = "1.3.3"
bs58 = "0.4.0"
chrono = { version = "0.4.11", features = ["serde"] }
crossbeam-channel = "0.5"
dashmap = { version = "4.0.2", features = ["rayon", "raw-api"] }
etcd-client = { version = "0.9.0", features = ["tls"]}
fs_extra = "1.2.0"
hex = "0.4.1"
histogram = "0.6.9"
itertools = "0.10.1"
log = "0.4.14"
lru = "0.7.1"
prost = "0.10.0"
rand = "0.7.0"
rand_chacha = "0.2.2"
raptorq = "1.6.4"
rayon = "1.5.1"
retain_mut = "0.1.5"
serde = "1.0.130"
serde_derive = "1.0.103"
solana-bloom = { path = "../bloom", version = "=1.9.15" }
solana-client = { path = "../client", version = "=1.9.15" }
solana-entry = { path = "../entry", version = "=1.9.15" }
solana-geyser-plugin-manager = { path = "../geyser-plugin-manager", version = "=1.9.15" }
solana-gossip = { path = "../gossip", version = "=1.9.15" }
solana-ledger = { path = "../ledger", version = "=1.9.15" }
solana-logger = { path = "../logger", version = "=1.9.15" }
solana-measure = { path = "../measure", version = "=1.9.15" }
solana-metrics = { path = "../metrics", version = "=1.9.15" }
solana-net-utils = { path = "../net-utils", version = "=1.9.15" }
solana-perf = { path = "../perf", version = "=1.9.15" }
solana-poh = { path = "../poh", version = "=1.9.15" }
solana-program-runtime = { path = "../program-runtime", version = "=1.9.15" }
solana-rpc = { path = "../rpc", version = "=1.9.15" }
solana-replica-lib = { path = "../replica-lib", version = "=1.9.15" }
solana-runtime = { path = "../runtime", version = "=1.9.15" }
solana-sdk = { path = "../sdk", version = "=1.9.15" }
solana-frozen-abi = { path = "../frozen-abi", version = "=1.9.15" }
solana-frozen-abi-macro = { path = "../frozen-abi/macro", version = "=1.9.15" }
solana-send-transaction-service = { path = "../send-transaction-service", version = "=1.9.15" }
solana-storage-proto = { path = "../storage-proto", version = "=1.9.15" }
solana-streamer = { path = "../streamer", version = "=1.9.15" }
solana-transaction-status = { path = "../transaction-status", version = "=1.9.15" }
solana-vote-program = { path = "../programs/vote", version = "=1.9.15" }
tempfile = "3.2.0"
thiserror = "1.0"
solana-rayon-threadlimit = { path = "../rayon-threadlimit", version = "=1.9.15" }
sys-info = "0.9.1"
tokio = { version = "1", features = ["full"] }
trees = "0.4.2"

[dev-dependencies]
jsonrpc-core = "18.0.0"
jsonrpc-core-client = { version = "18.0.0", features = ["ipc", "ws"] }
jsonrpc-derive = "18.0.0"
jsonrpc-pubsub = "18.0.0"
matches = "0.1.9"
reqwest = { version = "0.11.6", default-features = false, features = ["blocking", "rustls-tls", "json"] }
serde_json = "1.0.72"
serial_test = "0.5.1"
solana-program-runtime = { path = "../program-runtime", version = "=1.9.15" }
solana-stake-program = { path = "../programs/stake", version = "=1.9.15" }
solana-version = { path = "../version", version = "=1.9.15" }
static_assertions = "1.1.0"
systemstat = "0.1.10"

[build-dependencies]
rustc_version = "0.4"

[[bench]]
name = "banking_stage"

[[bench]]
name = "cluster_info"

[[bench]]
name = "gen_keys"

[[bench]]
name = "sigverify_stage"

[[bench]]
name = "retransmit_stage"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
